# Generated by Django 3.2.5 on 2022-03-29 20:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('terms_condition', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fraud_alert', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('disclaimer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faq', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('help_support', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
