# Generated by Django 3.2.5 on 2022-03-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='data_policy',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='help_support',
        ),
    ]
